.PHONY: clean All

All:
	@echo "----------Building project:[ SimuladorFisica - Debug ]----------"
	@cd "SimuladorFisica" && "$(MAKE)" -f  "SimuladorFisica.mk"
clean:
	@echo "----------Cleaning project:[ SimuladorFisica - Debug ]----------"
	@cd "SimuladorFisica" && "$(MAKE)" -f  "SimuladorFisica.mk" clean
